### ISSUE TITLE
Problem in chainer-caption

### ISSUE THREAD

**Issue by j2233ack** [apple2373/chainer-caption#2]
I have installed all the dependencies correctly.
I tried reinstalling it both form pip and source code. I tried editing the source code too.

Traceback (most recent call last):
  File "sample_code_beam.py", line 44, in <module>
    first_word= args.lang,
  File "./code/CaptionGenerator.py", line 43, in __init__
    self.index2token=self.parse_dic(dictonary_place)
  File "./code/CaptionGenerator.py", line 69, in parse_dic
    if isinstance(json_file['words'], list):
KeyError: 'words'

**Comment by apple2373** [comment]
Which language did you use for caption?  I think you are using non-English language. If it is English, it should work. 

Anyway, I fixed the bug. It should work with non-english language now.

**Comment by j2233ack** [comment]
I just ran to "I just want to generate caption!"

**Comment by apple2373** [comment]
I see. All four commands shown in that section should work now.
