### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by j2233ack** [apple2373/chainer-caption#4]
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Comment by apple2373** [comment]
ok, I never had this issue but thanks for reporting this!

**Comment by j2233ack** [comment]
Can you give me some advice to tell me how to do it?
Thanks!

**Comment by apple2373** [comment]
This looks like a problem of numpy installation so it's a bit hard to say something.  Did you use Anaconda (https://www.continuum.io/downloads)? It will automatically take care of everything for python environment. So install Anaconda, and install chainer as I showed in the readme. Then it should work.

**Comment by j2233ack** [comment]
Thank you! But there are new questions as follows:

Traceback (most recent call last):
  File "sample_code_beam.py", line 12, in <module>
    import chainer 
ImportError: No module named chainer

**Comment by j2233ack** [comment]
The above action is running under the CPU

**Comment by apple2373** [comment]
so you need to install chainer . Try this command. 
pip install chainer==1.19.0

**Comment by j2233ack** [comment]
I have installed chainer 1.19.0
as follows:
Requirement already satisfied: chainer==1.19.0 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages (from chainer==1.19.0)
Requirement already satisfied: filelock in /usr/local/lib/python2.7/dist-packages (from chainer==1.19.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/dist-packages (from chainer==1.19.0)
Requirement already satisfied: nose in /usr/lib/python2.7/dist-packages (from chainer==1.19.0)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from chainer==1.19.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf->chainer==1.19.0)

**Comment by apple2373** [comment]
Then you should be able to run my code....

**Comment by divssrivs** [comment]
@j2233ack did you ever find a solve to this? I am experiencing the same issue.

**Comment by j2233ack** [comment]
@divssrivs Sorry, I didn't continue later.
